micronaut:
  application:
    name: acme-contact
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000

jackson:
  property-naming-strategy: SNAKE_CASE